---
vars:
  region: "%{hiera('region')}"
  private_network_cidr: "%{hiera('private_network_cidr')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  cluster_instance_ssh_public_key_path: "%{cwd}/config/secrets/keys/cluster/ssh.public"
  cluster_instance_type: "t2.medium"
  cluster_minimum_size: 1
  cluster_maximum_size: 2
  cluster_desired_capacity: 1

  cluster_instance_root_block_device_size: 30
  cluster_instance_docker_block_device_size: 30

  state_bucket: "%{hiera('components_bucket_name')}"
  network_state_key: "%{hiera('network_state_key')}"

backend_config:
  bucket: "%{hiera('components_bucket_name')}"
  key: "%{hiera('cluster_state_key')}"
  region: "%{hiera('region')}"
