---
vars:
  region: "%{hiera('region')}"
  vpc_cidr: "%{hiera('vpc_cidr')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  state_bucket: "%{hiera('components_bucket_name')}"
  common_state_key: "%{hiera('common_state_key')}"

backend_config:
  bucket: "%{hiera('components_bucket_name')}"
  key: "%{hiera('network_state_key')}"
  region: "%{hiera('region')}"
