---
vars:
  region: "%{hiera('region')}"
  private_network_cidr: "%{hiera('private_network_cidr')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  cluster_instance_type: "%{hiera('cluster_instance_type')}"

  cluster_instance_ssh_public_key_path: "%{hiera('cluster_instance_ssh_public_key_path')}"

  cluster_minimum_size: "%{hiera('cluster_minimum_size')}"
  cluster_maximum_size: "%{hiera('cluster_maximum_size')}"
  cluster_desired_capacity: "%{hiera('cluster_desired_capacity')}"

  cluster_instance_root_block_device_size: "%{hiera('cluster_instance_root_block_device_size')}"
  cluster_instance_docker_block_device_size: "%{hiera('cluster_instance_docker_block_device_size')}"

  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_key: "%{hiera('network_state_key')}"

backend_config:
  bucket: "%{hiera('cluster_state_bucket_name')}"
  key: "%{hiera('cluster_state_key')}"
  region: "%{hiera('region')}"
  encrypt: "true"
